### ISSUE TITLE
Expo 51 Android build failed

### ISSUE THREAD

**Issue by davidcarboni** [achorein/expo-share-intent#61] opened 2024-05-09 13:29 UTC
**Describe the bug**

I've just upgraded to Expo 51 and running a development build. The build failed and mentioned expo-share-intent so I thought I'd share (could be my issue):

FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* Where:
Script '/home/expo/workingdir/build/app/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 408
* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-share-intent'.
   > Failed to notify project evaluation listener.
      > compileSdkVersion is not specified. Please add it to build.gradle
      > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================
2: Task failed with an exception.
-----------
* Where:
Script '/home/expo/workingdir/build/app/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 85
* What went wrong:
A problem occurred configuring project ':expo'.
> Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================
BUILD FAILED in 2m 42s

**Environment**

info Fetching system and libraries information...
System:
  OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Memory: 4.25 GB / 15.20 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.18.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Additional context**

- expo version (ex: 49) : 51.0.1
- using firebase : no
- using static build : yes / no
- routing : react-navigation
- package version (ex: 1.2.0) : ^1.1.0
- platform target : Android (and iOS)
- device : simulator & real device
- type: expo build

**Comment by joacub** [comment] 2024-05-09 17:24
same here

**Comment by achorein** [comment] 2024-05-09 18:15
Duplicate of #58

**Comment by achorein** [comment] 2024-05-09 18:54
Expo 51 is now supported in the v2.0.0 release !

**Closed by achorein** 2024-05-09 18:54 UTC

**Comment by davidcarboni** [comment] 2024-05-09 21:53
Amazing! 
Thank you so much :rocket: 
Just updated.
#hero
